# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfTlwMGQ-EKktgzuC6d5lyPZghOHtkBr
"""

import pandas as pd
data={'text':
 ["i love this product!",
  "this is the worst",
  "its was ok not great",
  "absoulutly amazing",
   "i didnt like",
    "just average"],
  'sentiment':
       ["positive",
        "negative",
        "neutral",
        "positive",
        "negative",
        "neutral"
                   ]}
df=pd.DataFrame(data)
df.head()

